language: node_js

node_js:
- "8.11.1"

sudo: required

os:
  - osx

env:
  - TARGET_ARCH=x64

services:
  - docker

osx_image: xcode9.0

cache:
  directories:
    - node_modules

script:
  - npm install
  - npm run dist
